// All Subscribers
GET http://localhost:3000/subscribers

###

// Specified Subscriber
GET http://localhost:3000/subscribers/id

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Tanapat Jeensamran",
    "subscribedToChannel": "Web Dev Simplified"
}

###

PATCH http://localhost:3000/subscribers/6239889e6a7ca8ab1b2e3a05
Content-Type: application/json

{
    "name": "Homer"
}

###

DELETE http://localhost:3000/subscribers/623988bb6a7ca8ab1b2e3a07

###

GET http://testrest69.app.ruk-com.cloud/subscribers

###

POST http://testrest69.app.ruk-com.cloud/subscribers
Content-Type: application/json

{
    "name": "Tanapat Jeensamran",
    "subscribedToChannel": "Gawr Gura"
}